# Generated by Django 2.2.6 on 2019-10-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='contents',
            field=models.TextField(verbose_name='내용'),
        ),
    ]
